# Generated by Django 6.0.4 on 2026-04-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.TextField(blank=True, null=True)),
                ('agent', models.TextField(blank=True, null=True)),
                ('order_customer', models.TextField(blank=True, null=True)),
                ('customer_description', models.TextField(blank=True, null=True)),
                ('destination_customer', models.TextField(blank=True, null=True)),
                ('destination_id', models.TextField(blank=True, null=True)),
                ('destination_description', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('country_description', models.TextField(blank=True, null=True)),
                ('selling_type', models.TextField(blank=True, null=True)),
                ('sub_seling_type', models.TextField(blank=True, null=True)),
                ('line', models.TextField(blank=True, null=True)),
                ('order_no', models.TextField(blank=True, null=True)),
                ('po_number', models.TextField(blank=True, null=True)),
                ('family_group', models.TextField(blank=True, null=True)),
                ('family_group_description', models.TextField(blank=True, null=True)),
                ('product_group', models.TextField(blank=True, null=True)),
                ('product_group_description', models.TextField(blank=True, null=True)),
                ('style', models.TextField(blank=True, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('material_description', models.TextField(blank=True, null=True)),
                ('measure', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('drop_value', models.TextField(blank=True, null=True)),
                ('variant_1', models.TextField(blank=True, null=True)),
                ('variant_2', models.TextField(blank=True, null=True)),
                ('label_1', models.TextField(blank=True, null=True)),
                ('label_2', models.TextField(blank=True, null=True)),
                ('cites', models.TextField(blank=True, null=True)),
                ('luxury', models.TextField(blank=True, null=True)),
                ('delivery_modality', models.TextField(blank=True, null=True)),
                ('delivery_method', models.TextField(blank=True, null=True)),
                ('delivery_group', models.TextField(blank=True, null=True)),
                ('delivery_from', models.TextField(blank=True, null=True)),
                ('delivery_to', models.TextField(blank=True, null=True)),
                ('customer_priority', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('order_qty', models.FloatField(blank=True, null=True)),
                ('order_value', models.FloatField(blank=True, null=True)),
                ('cancelled_qty', models.FloatField(blank=True, null=True)),
                ('cancelled_qty_value', models.FloatField(blank=True, null=True)),
                ('in_work_in_progress_qty', models.FloatField(blank=True, null=True)),
                ('in_work_in_progress_value', models.FloatField(blank=True, null=True)),
                ('stock_in_qty', models.FloatField(blank=True, null=True)),
                ('stock_in_value', models.FloatField(blank=True, null=True)),
                ('ready_qty', models.FloatField(blank=True, null=True)),
                ('ready_value', models.FloatField(blank=True, null=True)),
                ('picking_list_qty', models.FloatField(blank=True, null=True)),
                ('picking_list_value', models.FloatField(blank=True, null=True)),
                ('invoice_qty', models.FloatField(blank=True, null=True)),
                ('invoice_value', models.FloatField(blank=True, null=True)),
                ('ready_to_pick_100_qty', models.FloatField(blank=True, null=True)),
                ('ready_to_pick_100_value', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
